### PR TITLE
Fixed bug with cell_modifiers being printed in comments. 

### LINKED ISSUE #483: Moving parameters from Data block to Cell block neglects in-line comments
**Describe the bug**

One can use `MCNP_Problem.print_in_data_block` to control whether a given cell parameter is written in the respective cell cards in the Cell block, or in a monolithic data card in the Data block.

When cell parameters in an existing input file are moved _from_ the Data block _to_ the Cell block, they are placed at the end of the relevant line as long as they fit. This results in them being after any `$ in-line comment`. When the parameters do fit on the line, they must be placed before the comment. 

**To Reproduce**

``` python
import montepy
deck = montepy.read_input("imp_cell.imcnp")
deck.print_in_data_block["IMP"] = False
deck.write_to_file("imp_data.imcnp", overwrite=True)
```

**MCNP input file snippet**

##### imp_cell.imcnp

```
Cell card printing error
C Cells
1 0  -100 $ 
2 0  +100 $ graveyard 

C Surfaces
100 so 10

C Data Cards
mode n
IMP:n 1 0 
```

##### imp_data.imcnp

```
Cell card printing error
C Cells
1 0  -100 $ IMP:n=1 
2 0  +100 $ graveyard IMP:n=0 

C Surfaces
100 SO 10

C Data Cards
mode n


```

**Version**

 - Versions 0.2 - 0.3.2

### PR DESCRIPTION
**Pull request by MicahGale**
# Description

This handles the case where cell modifiers when moved to the cell block may show up behind a comment, which I have dubbed a "graveyard" comment due to a bit of confusion.

To solve this:

1. Introduced a method to check for these graveyard comments in the tree.
2. Appended a `\n` and spaces after that comment
3. Made a system for cell modifiers when formatting to know if there is going to be more information after themselves.
4. changed how blank lines in cell inputs are removed. 

Fixes #483

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Comment by tjlaboss** [comment]
FYI "graveyard" is just shorthand for the zero-importance region outside the main geometry, effectively equivalent to a vacuum boundary condition on the bounding surface(s)

**Comment by MicahGale** [comment]
Oh lol. I thought it was comment that was a graveyard for information. It works here.

**Comment by tjlaboss** [comment]
where information goes to die

**Comment by MicahGale** [comment]
Waiting on figuring out this bug offline with @tjlaboss's models.

**Comment by MicahGale** [comment]
Ok I was able to replicate your issue @tjlaboss  is 83ef1d0

**Comment by tjlaboss** [comment]
Failing with certain cutting comments, like so:

```
99 0 1000:-1005 1010 
c Cutting comment followed by empty line
c
5 0 
      #99
      imp:n,p=3 $graveyard
c foo end comment
```

**Review by tjlaboss — APPROVED** [review]
Now it no longer breaks models models with comments!

New lines containing the cell modifier parameters are now inserted after following comments, which will be a future, non-critical issue.

**Pull request merged**
