### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by MicahGale**
# Features Added

* Added `clone` method to simplify making copies of objects (#469).

# Performance Improvement

* Fixed cyclic memory reference that lead to memory leak in `copy.deepcopy` (#514).
* Fixed O(N<sup>2</sup>) operation in how append works for object collections like Cells (#556).

# Bug Fixes

* Fixed bug with parsing an `EO` input (#551).
* Fixed a bug raised in an edge case when editing cell geometry, by making the error clearer (#558).
* Fixed bug with having a shortcut in a cell fill (#552).
* Fixed bug where file streams couldn't actually be read (#553).

# Support

* Added support for Python 3.13, and removed support for Python 3.8, and officially added support NumPy 1 & 2 (#548).

### CODE REVIEW

**Comment by tjlaboss** [comment]
Need to update the changelog and then we can release.

**Comment by MicahGale** [comment]
The changelog here?

**Comment by MicahGale** [comment]
Ohh I see the issue you are referring to I think. A section header got deleted.

**Comment by MicahGale** [comment]
NVM. The `#Next Version#` thing. That gets done manually by me with `.github/scripts/deploy.sh`. It's a bit jank but it works for now.

**Pull request merged**
