### PR TITLE
Overhaul how character encoding is handled. 

### LINKED ISSUE #186: Add option to just wing it with encoding
In #118 we changed over to only using ASCII encoding. Though in the wild many problems use other encoding schemes. We should either add an option to not use ASCII, which defaults to UTF-8, or to allow the user to specify whatever encoding they want to use.

### PR DESCRIPTION
**Pull request by MicahGale**
Adds:
- `MCNP_InputFile` to documentation site.
- Added encoding options when opening a file, and to `input_reader`
- Added script utility to strip out all non-ascii characters.
    this works by:
    - reading into UTF-8 with replace.
    - Replaced replaced characters with nothing or `' '`
    - Covert back to ascii. Anything about 128 also gets converted. 
 - Added utilities section to guide
 - Added FAQ that shows a typical stack trace

Needs still:

- [x] test for changes
- [x] graceful error handling for bad encoding
- [x] Document how to use this in user docs.
- [x] Add FAQ: what are encoding errors
- [x] Add doc strings

Closes #186, #334.

### CODE REVIEW

**Comment by MicahGale** [comment]
Actually how hard should we try with enforcing a valid encoding @tjlaboss? It should get pushed down to python really quick and handled that way.

**Comment by MicahGale** [comment]
I'm not sure I like the command: `change_to_ascii`

**Comment by MicahGale** [comment]
This also leads to the question: should we go back and support UTF-8 as the default? I am learning that ASCII is very annoying.

**Comment by MicahGale** [comment]
Artifacts that include the updated website: https://github.com/idaholab/MontePy/actions/runs/7585620985?pr=333

**Comment by MicahGale** [comment]
We changed the behavior from strictly enforcing encoding to replacing all non-ascii characters with spaces. This is the most conservative approach. Using default python `replace` would have lead to a lot of `?` which would break syntax. Extra spaces randomly throughout should generally have no impact on the semantic meaning of a model. If a user has a problem with formatting being messed up they can always just delete the offending non-ascii chars.

**Comment by MicahGale** [comment]
Quick thought: does the character stripper handle `\r\n` properly? There are reports that mixing and matching line ends in a file will lead to complications.

**Comment by tjlaboss** [comment]
Should be able to review this week.

**Comment by MicahGale** [comment]
Should a warning be issued every time a character is converted?

**Comment by tjlaboss** [comment]
No. If it is important to warn about specific character conversions, I'd put them all in a single warning message.

**Review by tjlaboss — APPROVED** [review]
The first official MontePy script!

**Comment by MicahGale** [comment]
Thanks for the review. I'm going to wait until merging #336.

**Pull request merged**
