### PR TITLE
Add robits

### LINKED ISSUE #478: Create robots.txt
I started tracking Google indexing of montepy.org. Google appears to only be indexing the top level page, and nothing else. It seems that Google needs approval to index the whole site with a `robots.txt` file: https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt

### PR DESCRIPTION
**Pull request by MicahGale**
# Description

This adds support for robits to our documentation website via `robots.txt` and by creating a `sitemap.xml`, because

why not

Fixes #478.

# Checklist

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by MicahGale** [comment]
Can confirm that `robots.txt` and `sitemap.xml` are provided in this build artifact: 
[website.zip](https://github.com/user-attachments/files/16567188/website.zip)

**Comment by tjlaboss** [comment]
(\\/)°,,,,° (\\/) whoop whoop whoop whoop whoop whoop 

I will learn a bit about robits.txt to review this.

**Comment by MicahGale** [comment]
:crab: or wait: :lobster:?

**Review by tjlaboss — APPROVED** [review]
Merge? Why not[,] Zoidberg?

**Pull request merged**
