### PR TITLE
Pass changelog-test when no code is modified

### LINKED ISSUE #436: Add logic to CI to disable changelog test
**Is your feature request related to a problem? Please describe.**
Changes to meta things in the repository do not need to result in updates to the changelog. Modifications strictly to testing, documentation, license, etc. should be exempt from `changelog-test`.

**Describe the solution you'd like and alternatives you've considered**

Ideas, in order of descending preference:

 * Within `changelog-test`, check if modifications have been made to the `montepy/` module directory. If not, automatically pass.
 * Do not run `changelog-test` based on branch name wildcards, such as `doc-*` 
 * Add a magic keyword such as `no-changelog`

### PR DESCRIPTION
**Pull request by tjlaboss**
# Description

Add some additional logic to check if any code in `montepy/` was updated. 

Todo: squash

Fixes #436 

# Checklist

- [x] I have tested the CI.

### CODE REVIEW

**Comment by tjlaboss** [comment]
So far so good: changelog-test now passes when no code is modified.

**Comment by tjlaboss** [comment]
Changelog test now fails if something is modified in _montepy/_ and changelog.rst wasn't updated.

**Review by MicahGale — APPROVED** [review]
LGTM. We'll have to see on my branch if this works as expected when both have changed.

**Comment by MicahGale** [comment]
>fix bad yaml in main.yml 

I've been there... a lot

**Pull request merged**
