### PR TITLE
Fix bug with hidden vertical input mode. 

### PR DESCRIPTION
**Pull request by MicahGale**
Vertical mode detection accidentally wasn't considering comments. This fixed this logic.

Fixes #370.

### CODE REVIEW

**Comment by MicahGale** [comment]
@sterlingbutters would you like to review this one?

**Comment by SterlingButters** [comment]
@MicahGale I trust you 😎

**Comment by MicahGale** [comment]
Thanks for the confidence @SterlingButters. Though the expectation is that no code gets merged without someone besides the author reviewing it, no matter what. The general things we look for are covered by the [merge checklist](https://idaholab.github.io/MontePy/developing.html#merge-checklist) and the [developer philosophy](https://idaholab.github.io/MontePy/developing.html#design-philosophy).

So would you be willing to complete this required review? If not, no worries we can have someone else review it.

**Review by SterlingButters — APPROVED** [review]
Looks good to me

**Comment by MicahGale** [comment]
Thanks for the review.

**Pull request merged**
