### PR TITLE
Enable Pickling of Tallies

### LINKED ISSUE #463: Error pickling MCNP_Problem: Cannot pickle 'generator' object
Cannot pickle `montepy.MCNP_Problem` objects.

**Describe the bug**

Since v0.3.0, can no longer pickle `montepy.MCNP_Problem` for more complicated input decks. The `MCNP_Problem` contains an unpicklable generator object. Rolling back to v0.2.10 fixes this.

This occurs when the problem contains **tallies** (possibly other non-implemented data cards?).

This is not caught by _tests/test_interface.py::TestBrinyFermentation_ .

**To Reproduce / Error Message**

```python
>>> deck = montepy.read_input("path/to/input.imcnp")
>>> with open("path/to/pickle.pkl", 'wb') as pkl:
...    pickle.dump(deck, pkl)
TypeError: cannot pickle 'generator' object
```

**MCNP input file snippet**

```
MCNP Test Model for Tallies
1 1 20 -1000  imp:n,p=1 U=350 trcl=5
2 2 8  -1005  imp:n=1    imp:p=0.5
3 3 -1  1000 1005 -1010 imp:n,p=1
99 0 1010     imp:n,p=0
5 0   #99     imp:n,p=3 fill=350 (1 0 0 ) 

C surfaces
1000 SO 1
1005 RCC 0 1.5 -0.5 0 0 1 0.25
1010 SO 3

C data
C materials
C UO2 5 atpt enriched
m1        92235.80c           5 &
92238.80c          95
C Iron
m2        26054.80c        5.85
          26056.80c       91.75
          26057.80c        2.12
          26058.80c        0.28 
C water
m3        1001.80c           2
          8016.80c           1
MT3 lwtr.23t h-zr.20t h/zr.28t
C
C Tallies --> This breaks MontePy!
f7:n 1
C
C execution
ksrc 0 0 0 
kcode 100000 1.000 50 1050
phys:p j 1 2j 1
mode n p 
vol NO 2J 1 1.5 J
```

**Versions**

 - 0.3.0,
 -  0.3.1, 
 - 0.3.2

### PR DESCRIPTION
**Pull request by tjlaboss**
# Description

This PR first demonstrated failures for inputs involving tallies. It has since been expanded to resolve #463.

## Update from @MicahGale, and fixes:

This bug is related to `sly` `Yacc` descended objects. Basically they can end up in states where they cannot be pickled. The first issue is that sometimes they keep `parser.tokens` as a generator. The other is that they will store a `parser.production` which has a lot of `lambda` functions, and closures. None of these are allowed for copying or pickling. To fix this I:

1. blanked out `parser.tokens` when complete.
2. Prevented `_parser` from being pickled as it isn't needed. 

Fixes #463. 

# checklist 
* [x]  I have performed a self-review of my own code
* [x] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Comment by MicahGale** [comment]
Might fix this one day.

**Comment by MicahGale** [comment]
Ok didn't fix it. But at least now there isn't infinite recursion to deal with while debugging.

**Comment by tjlaboss** [comment]
progress

**Comment by MicahGale** [comment]
I know you opened this PR @tjlaboss, but want to review it since I did all the fixes here?

**Comment by tjlaboss** [comment]
Approved.

**Review by MicahGale — APPROVED** [review]

**Pull request merged**
